# Generated by Django 2.0.7 on 2018-07-24 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20180718_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='class_slot_1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_slot_1', to='games.CharacterClass'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='class_slot_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_slot_2', to='games.CharacterClass'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='race_slot_1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_slot_1', to='games.CharacterRace'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='race_slot_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_slot_2', to='games.CharacterRace'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
