# Generated by Django 2.0.7 on 2018-07-26 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20180724_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='order',
            field=models.IntegerField(blank=True, default=True, null=True, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='gamer',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
