# Generated by Django 2.0.7 on 2018-07-26 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20180726_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='order',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
