# Generated by Django 2.0.7 on 2018-09-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20180726_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamer',
            options={'ordering': ['id']},
        ),
    ]
